language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
before_script:
  - npm prune
after_success:
  - npm run build
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5.1
before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
