title: DADI Documentation
email: team@dadi.tech
description: > # this means to ignore newlines until "baseurl:"
  Documentation for all DADI products.
baseurl: "/docs" # the subpath of your site, e.g. /blog
url: "http://dadi.github.io/docs/" # the base hostname & protocol for your site
twitter_username: dadi
github_username:  dadi
exclude: ['node_modules']
baseurl: "/docs"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Serving
detach:  false
port:    4900
host:    0.0.0.0
