title: DADI Documentation
email: team@dadi.tech
description: > # this means to ignore newlines until "baseurl:"
  Documentation for all DADI products.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: dadi
github_username:  dadi

# Locations
source:       .
destination:  ./_jekyll/_site
plugins_dir:  ./_jekyll/_plugins
layouts_dir:  ./_jekyll/_layouts
data_dir:     ./_jekyll/_data
includes_dir: ./_jekyll/_includes

defaults:
  -
    values:
      layout: "default"

# SCSS
sass:
    sass_dir: ./css

collections:
  docs:
    output: true